image:
  enabled: true # works with github workflow
  test_command: >-
    pytest src/tests/
    --cov=src
    --cov-report=xml:/app/coverage/coverage.xml

ecs:
  desired_count: 0 # Note this currently will not work because we block lifecycle in Tofu for desired count
  cluster: cdap-test-tftesting
