image:
  enabled: true # works with github workflow
  test_command: "pytest" # works with github workflow

ecs:
  enabled: true # TODO set up ephemeral tag to bring down tasks but preserve the application image tag
  lifecycle: ephemeral
  cluster: cdap-test-tftesting
