shares:
  bb:
    envs:
     - prod
     - sandbox
    principal_ssm_key: "aws_account_id"
    s3_access:
      envs:
        - prod
      write_role_arn_ssm_key: "lambda_role_arn"
      read_account_id_ssm_path: "external/dasg_insights/sensitive/aws_account_id"
      read_role_name: "service-role/aws-quicksight-service-role-v0"
  bfd:
    envs:
      - prod
      - sandbox
    principal_ssm_key: "aws_account_id"
    