name: Install sops
description: Sets up https://api.github.com/repos/getsops/sops
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Configuration
        SOPS_VERSION="v3.11.0" # Specify the desired SOPS version
        ARCH="amd64"           # Set the architecture
        OS="linux"             # Set the operating system
        TMPDIR=$(mktemp -d)
        cd $TMPDIR
        
        # URL for the SOPS release files
        BASE_URL="https://github.com/getsops/sops/releases/download"
        BINARY_NAME="sops-${SOPS_VERSION}.${OS}.${ARCH}"
        CHECKSUMS_FILE="sops-${SOPS_VERSION}.checksums.txt"
        CHECKSUMS_PEM="sops-${SOPS_VERSION}.checksums.pem"
        CHECKSUMS_SIG="sops-${SOPS_VERSION}.checksums.sig"
        
        if cosign version > /dev/null; then
          #Download the binary and checksums file
          echo "Downloading SOPS version ${SOPS_VERSION}..."
          curl -SsLO "${BASE_URL}/${SOPS_VERSION}/${BINARY_NAME}"
          curl -SsLO "${BASE_URL}/${SOPS_VERSION}/${CHECKSUMS_FILE}"
          curl -SsLO "${BASE_URL}/${SOPS_VERSION}/${CHECKSUMS_PEM}"
          curl -SsLO "${BASE_URL}/${SOPS_VERSION}/${CHECKSUMS_SIG}"
          
          echo "Verifying checksum..."
          cosign verify-blob ${CHECKSUMS_FILE} \
            --certificate ${CHECKSUMS_PEM} \
            --signature ${CHECKSUMS_SIG} \
            --certificate-identity-regexp=https://github.com/getsops \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com
          SOPS_SIG_CHECK=$?
         
          if [ "$SOPS_SIG_CHECK" -eq "0" ]; then
            echo "signatures verified"
            #Move the binary to /usr/local/bin/sops
            echo "Installing SOPS"
            mv sops-v3.11.0.linux.amd64 /usr/local/bin/sops
            #Make the binary executable
            echo "Setting executable permissions..."
            chmod +x /usr/local/bin/sops
          else
            echo "signature verification failed"
            exit 1
          fi
        else
          echo "install cosign for signature verification"
        fi
