name: Install sops
description: Sets up https://api.github.com/repos/getsops/sops
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        
        set -eo pipefail
        
        # Configuration
        SOPS_VERSION="v3.11.0" # Specify the desired SOPS version
        ARCH="x64"    # Set the architecture
        OS="linux"             # Set the operating system
        TMPDIR=$(mktemp -d)
        cd $TMPDIR
        
        # URL for the SOPS release files
        BASE_URL="https://github.com/getsops/sops/releases/download"
        BINARY_NAME="sops-${SOPS_VERSION}.${OS}.${ARCH}"
        CHECKSUMS_FILE="sops-${SOPS_VERSION}.checksums.txt"
        
        # --- Main installation logic ---
        
        # 1. Download the binary and checksums file
        echo "Downloading SOPS version ${SOPS_VERSION}..."
        curl -LO "${BASE_URL}/${SOPS_VERSION}/${BINARY_NAME}"
        curl -LO "${BASE_URL}/${SOPS_VERSION}/${CHECKSUMS_FILE}"

        # 2. Verify the checksum
        echo "Verifying checksum..."
          cosign verify-blob sops-v3.11.0.checksums.txt \
          --certificate sops-v3.11.0.checksums.pem \
          --signature sops-v3.11.0.checksums.sig \
          --certificate-identity-regexp=https://github.com/getsops \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com
        
        # 3. Move the binary to $HOME/.sops
        echo "Installing SOPS to $HOME/.sops..."
         mv $TMPDIR $HOME/.sops
          echo "PATH=$HOME/.sops:$PATH" >> "$GITHUB_ENV"
          echo "SOPS_INSTALL=true" >> "$GITHUB_ENV"
          echo "sops installed"
        
        # 4. Make the binary executable
        echo "Setting executable permissions..."
        sudo chmod +x $HOME/.sops
        
        # 5. Clean up downloaded files
        echo "Cleaning up temporary files..."
        rm "${CHECKSUMS_FILE}"
        
        # 6. Verify the installation
        echo "SOPS installation complete. Checking version:"
        sops --version
