name: Install yq
description: Sets up yq yaml parser - https://github.com/mikefarah/yq
outputs:
  yq-latest-version:
    description: Get the version we will download.
    value: ${{ steps.get-version.outputs.yq-latest-version }}
  checksum:
    description: Checksum for the downloaded yq binary.
    value: ${{ steps.get-checksum.outputs.checksum }}

runs:
  using: composite
  steps:
    - name: get-version
      shell: bash
      run: |
        VERSION=$(curl -sL https://api.github.com/repos/mikefarah/yq/releases/latest | grep "tag_name" | cut -d '"' -f 4 | sed 's/v//')
        echo "yq-latest-version=${VERSION}" >> $GITHUB_OUTPUT
    - name: get-checksum
      shell: bash
      run: |
        # Create a temporary directory
        TMP_CHECKSUM_DIR=$(mktemp -d)
        cd "$TMP_CHECKSUM_DIR"
        CHECKSUM_DOWNLOAD_URL="https://github.com/mikefarah/yq/releases/download/v${{ steps.get-version.outputs.yq-latest-version }}/checksums"
        CHECKSUM_HASH_DOWNLOAD_URL="https://github.com/mikefarah/yq/releases/download/v${{ steps.get-version.outputs.yq-latest-version }}/checksums_hashes_order"
        
        curl -sSL "$CHECKSUM_DOWNLOAD_URL" -o "checksums"
        curl -sSL "$CHECKSUM_HASH_DOWNLOAD_URL" -o "checksums_hashes_order"
        
        if [ ! -f "checksums_hashes_order" ]; then
        echo "This script requires checksums_hashes_order to run"
        echo "Download the file from https://github.com/mikefarah/yq/releases/ for the version of yq you are trying to validate"
        exit 1
        fi
        
        if [ ! -f "checksums" ]; then
        echo "This script requires the checksums file to run"
        echo "Download the file from https://github.com/mikefarah/yq/releases/ for the version of yq you are trying to validate"
        exit 1
        fi
        
        
        grepMatch=$(grep -m 1 -n "SHA-256" checksums_hashes_order)
        if [ "$grepMatch" == "" ]; then
        echo "Could not find hash algorithm '"SHA-256"' in checksums_hashes_order"
        exit 1
        fi
        
        set -e
        
        lineNumber=$(echo "$grepMatch" | cut -f1 -d:)
        
        realLineNumber="$(($lineNumber + 1))"
        
        checksum=$(grep "$file" checksums | sed 's/  /\t/g' | cut -f1,$realLineNumber)
        echo (Got checksum $checksum)

    - name: download-yq
      shell: bash
      run: |
        ARCH="linux_amd64"
        DOWNLOAD_URL="https://github.com/mikefarah/yq/releases/download/v${{ steps.get-version.outputs.yq-latest-version }}/yq_${ARCH}"

        INSTALL_PATH="/usr/local/bin/yq"
        
        # Create a temporary directory
        TMP_DIR=$(mktemp -d)
        cd "$TMP_DIR"
        
        echo "Downloading yq version ${{ steps.get-version.outputs.yq-latest-version }}..."
        
        # Download the yq binary
        curl -sSL "$DOWNLOAD_URL" -o "yq_binary"
        
        if shasum -a 256 -c $ --ignore-missing; then
          mv "yq_binary" "$INSTALL_PATH"
          sudo chmod +x "$INSTALL_PATH"
          echo "yq installed to $INSTALL_PATH"
          rm -rf "$TMP_DIR"
        else
          echo "checksum check failed"
          rm -rf "$TMP_DIR"
          exit 1
        fi
