sonar.projectKey=cdap-aws-params-env-action
sonar.projectName=CDAP AWS Params Env Action
sonar.ci.autoconfig.disabled=true
sonar.sources=src
sonar.tests=__tests__
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=dist/**,lib/**,node_modules/**
sonar.test.inclusions=**/*.test.ts
