sonar.projectKey=aws-params-env-action
sonar.projectName=aws-params-env-action
sonar.sources=src
sonar.tests=__tests__
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=dist/**,lib/**,node_modules/**
sonar.test.inclusions=**/*.test.ts
