output "repo" {
  description = "The ECR Repo object generated by ToFu."
  value       = aws_ecr_repository.this
}

output "repo_lifecycle_policy" {
  description = "The ECR Lifecycle policy generated by ToFu."
  value       = aws_ecr_lifecycle_policy.this
}
