output "repo" {
  description = "The ECR Repo object generated by ToFu."
  value       = aws_ecr_repository.this
}

output "repo_lifecycle_policy" {
  description = "The ECR Lifecycle policy generated by ToFu."
  value       = aws_ecr_lifecycle_policy.this
}

output "image_tag" {
  description = "The currently deployed image tag, as last written by the build workflow"
  value       = aws_ssm_parameter.image_tag.value
}

output "image" {
  description = "The full image URI including the current tag — can be used directly when repo is established alongside ecs_service."
  value       = "${aws_ecr_repository.this.repository_url}:${aws_ssm_parameter.image_tag.value}"
}

output "image_version" {
  description = "Short git SHA used as dd_version"
  value       = aws_ssm_parameter.image_version.value
}
