shadow_mode: true

notifications:
  channels:
#    - "@victorops-cdap-team"
# FixMe Update with integrations provided

lambda:
  error_rate_threshold: 1

enabled:
  ecs: false
  sqs: false
  sns: false
  lambda: false
  s3: false
  rds: false
