/cdap/account/security_events_slack_renotify_after_days: 30
/cdap/account/security_events_slack_severity_list: CRITICAL,HIGH,MEDIUM
/cdap/sensitive/account/security_events_slack_webhook_url: https://hooks.slack.com/services/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
/cdap/sensitive/bucket-access-logs-bucket: bucket-access-logs-20250411172631068600000001
/cdap/sensitive/mgmt-vpc/cidr: 10.128.178.0/23
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-a: 13.217.185.142
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-b: 3.226.187.84
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-c: 52.55.143.28
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:202533514245:key/e32dffdb-97e7-4b64-b5cb-f6dc4e6fabca
      created_at: "2025-07-17T18:19:00Z"
      aws_profile: ""
    - arn: arn:aws:kms:us-east-1:202533514245:alias/cdap-mgmt
      created_at: "2025-07-17T18:19:00Z"
      aws_profile: ""
  encrypted_regex: sensitive
  mac_only_encrypted: true
  version: 3.10.2

