/cdap/account/security_events_slack_renotify_after_days: 30
/cdap/account/security_events_slack_severity_list: CRITICAL,HIGH,MEDIUM
/cdap/sensitive/account/security_events_slack_webhook_url: https://hooks.slack.com/services/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
/cdap/sensitive/bucket-access-logs-bucket:
/cdap/sensitive/mgmt-vpc/cidr:
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-a:
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-b:
/cdap/mgmt/public_nat_ipv4/sensitive/cdap-east-mgmt-c:
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:202533514245:key/e32dffdb-97e7-4b64-b5cb-f6dc4e6fabca
      created_at: "2025-07-17T18:19:00Z"
      aws_profile: ""
    - arn: arn:aws:kms:us-east-1:202533514245:alias/cdap-mgmt
      created_at: "2025-07-17T18:19:00Z"
      aws_profile: ""
  encrypted_regex: sensitive
  mac_only_encrypted: true
  version: 3.10.2

