#!/usr/bin/env bash

set -x

# Only bcda and dpc for now since each ab2d env is in its own account
apps="bcda dpc"
envs="dev test prod sbx"

for app in $apps; do
  export TF_VAR_app=$app
  for env in $envs; do
    export TF_VAR_env=$env
    terraform init -reconfigure -backend-config=../../backends/$TF_VAR_app-$TF_VAR_env.s3.tfbackend
    terraform import module.opt_out_import_lambda.aws_iam_role.lambda $TF_VAR_app-$TF_VAR_env-opt-out-import-lambda
  done
done
