#!/bin/bash
# Run checks on tofu files from git diff. Used in the tofu-checks workflow.
set -e

# When run on main, diff against the prior commit. When run on any
# other branch, diff against main.
ref="$([ "$(git branch --show-current)" == "main" ] && echo "HEAD^" || echo "main")"
echo "Using $ref for diff"

# Check formatting on all added or modified terraform/tofu files.
echo "Checking formatting on the following added or modified tf files:"
diff_tf="$(git diff --name-only --diff-filter=ACMR "$ref" -- '*.tf')"
echo "$diff_tf"
tofu fmt -check -diff $diff_tf

# Run checks in all affected terraform/tofu directories.
diff_dirs="$(git diff --name-only "$ref" -- '*.tf' | xargs dirname | sort | uniq)"
repo_root="$(git rev-parse --show-toplevel)"
for dir in $diff_dirs; do
  cd "$repo_root"
  [ ! -d "$dir" ] && continue # Skip if directory no longer exists
  cd "$dir"
  echo "Running validate on \"$dir\""
  tofu init -backend=false
  tofu validate
done
