cross_account_shares:
  bb:
    env_labels:
      - prod
      - sandbox

#  bfd:
#    env_labels:
#      - prod

key_permissions:
  api_key_manager: true
  org_config_manager: true
  users_manager      : true
