name: Sonarqube analysis for aws-params-env-action
description: Leverages sonarqube to scan for quality issues and then gate the workflow success based on any issues.

on:
  pull_request:
    paths:
      - 'actions/aws-params-env-action/**'
      - '!actions/aws-params-env-action/**.md'
  schedule:
    - cron: '31 7 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: actions/aws-params-env-action

jobs:
  sonarqube:
    runs-on: codebuild-cdap-${{ github.ref_name =='main' && 'prod' || 'non-prod' }}-${{github.run_id}}-${{github.run_attempt}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          fetch-depth: 0 # Sonarqube requirement

      - name: Assume role to AWS
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ github.ref_name =='main' && secrets.PROD_ACCOUNT || secrets.NON_PROD_ACCOUNT }}:role/delegatedadmin/developer/${{ github.ref_name =='main' && 'cdap-prod' || 'cdap-test' }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Retrieve Sonarqube credentials
        uses: ./actions/aws-params-env-action
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm ci

      - name: Run Sonarqube
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        with:
          projectBaseDir: actions/aws-params-env-action

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b #v1.2.0
        timeout-minutes: 5
        with:
          scanMetadataReportFile: actions/aws-params-env-action/.scannerwork/report-task.txt
