name: python-checks
description: Evaluates all python files using Snyk and Sonarqube.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'terraform/services/**/lambda_src/**/*.py'
      - 'terraform/services/**/lambda_src/**/requirements.txt'
      - 'terraform/modules/**/lambda_src/**/*.py'
      - 'terraform/modules/**/lambda_src/**/requirements.txt'
      - 'scripts/**/*.py'
      - 'scripts/**/requirements.txt'

jobs:
  python-checks:
    permissions:
      contents: read
      id-token: write
    runs-on: codebuild-cdap-${{ github.ref_name == 'main' && 'prod' || 'non-prod' }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.3.0
        with:
          fetch-depth: 0

      - name: Assume role to AWS
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ github.ref_name =='main' && secrets.PROD_ACCOUNT || secrets.NON_PROD_ACCOUNT }}:role/delegatedadmin/developer/${{ github.ref_name =='main' && 'cdap-prod' || 'cdap-test' }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Retrieve credentials
        uses: ./actions/aws-params-env-action
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            SNYK_TOKEN=/cdap/${{ github.ref_name =='main' && 'prod' || 'test' }}/snyk/api_token
            SONAR_HOST_URL=/sonarqube/url
            SONAR_TOKEN=/sonarqube/token

      - name: Install Snyk CLI while binary defaults to x86 and runners use arm64
        run: |
          curl -sSLo /usr/local/bin/snyk https://static.snyk.io/cli/latest/snyk-linux-arm64
          chmod +x /usr/local/bin/snyk
          snyk --version

      - name: Snyk Dependency Scan (snyk test)
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        run: snyk test --all-projects --exclude=.terraform,.snyk-cli,node_modules

      - name: Snyk Code Scan (snyk code test)
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        run: snyk code test --all-projects

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b #v1.2.0
        timeout-minutes: 5
