name: 'Scheduled Snyk Code Scan CDAP'

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  scheduled-snyk-code-scan-cdap:
    name: 'Trigger Scheduled Snyk Code Scan for CDAP'
    uses: CMSGov/CDAP/.github/workflows/snyk-code-scan.yml@a20fe20db1d116bb26f0b26e76b7d9fc0cdf3a55
    with:
      app: cdap
      ref: main
    secrets: inherit
