name: set-log-retention-checks (cloudwatch log retention)
description: Checks CDAP hosted check-log-retention for python vulnerabilities and code quality.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'scripts/set_log_retention/*.py'
      - 'scripts/set_log_retention/requirements.txt'

jobs:
  python-checks:
    uses: ./.github/workflows/python-checks-reusable.yml
    with:
      source_path: scripts/set_log_retention
      sonar_project_key: cdap-set-log-retention
      sonar_project_name: "CDAP Set Log Retention"
