name: sync-security-groups

on:
  workflow_dispatch: # Allow manual trigger
    inputs:
      private_branch:
        description: Which branch of the private repo to check out
        required: false
        type: string
        default: main

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  ip-set-sync:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    strategy:
      fail-fast: false
      matrix: # Only run once per account
        app: [bcda]
        env: [test, prod]
    steps:
      - name: Get AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            CI_GITHUB_TOKEN=/ci/github/token
      - name: Check out private repo
        uses: actions/checkout@v4
        with:
          repository: CMSgov/cdap-private
          token: ${{ env.CI_GITHUB_TOKEN }}
          ref: ${{ inputs.private_branch }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ contains(fromJSON('["dev", "test"]'), matrix.env) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT }}:role/delegatedadmin/developer/${{ matrix.app }}-${{ matrix.env }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run script to sync security groups
        run: |
          scripts/sync-security-groups zscaler-private
          scripts/sync-security-groups zscaler-public
