name: sync-ab2d-ip-set

on:
  workflow_dispatch: # Allow manual trigger
    inputs:
      env:
        required: false
        type: choice
        options:
          - dev
          - test
          - prod
        default: prod
      cidr_file:
        required: false
        type: string
        default: cidr/ab2d-customers.txt
      private_branch:
        description: Which branch of the private repo to check out
        required: false
        type: string
        default: main

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  waf-ip-sync:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - name: Get AWS params
        uses: cmsgov/cdap/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params: |
            CI_GITHUB_TOKEN=/ci/github/token
      - name: Check out private repo
        uses: actions/checkout@v4
        with:
          repository: CMSgov/cdap-private
          token: ${{ env.CI_GITHUB_TOKEN }}
          ref: ${{ inputs.private_branch }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ contains(fromJSON('["dev", "test"]'), inputs.env) && secrets.NON_PROD_ACCOUNT || secrets.PROD_ACCOUNT }}:role/delegatedadmin/developer/ab2d-${{ inputs.env }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run IP set sync script
        run: scripts/sync-ip-set --name=ab2d-$ENV-api-customers --scope=REGIONAL $CIDR_FILE
        env:
          ENV: ${{ inputs.env }}
          CIDR_FILE: ${{ inputs.cidr_file }}
