name: tf-test-sops-install
run-name: tf-test-sops-install

on:
  push:
    paths:
      - .github/workflows/tf-test-sops-install.yml

defaults:
  run:
    working-directory: ./terraform/services/kms-keys

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  check-sops:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    strategy:
      fail-fast: false
      matrix:
        app: [cdap]
        env: [mgmt]
    steps:
      - name: Install Cosign to verify sops install
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159
      - name: Install sops
        uses: cmsgov/cdap/actions/setup-sops@e4ee9a052bf99842147ea85a7208ed5458f9217b
      - name: Call SOPS
        run: |
          sops --version --check-for-updates && yq --version  --check-for-updates