name: tf-test-yq-install
run-name: tf-test-yq-install

on:
  push:
    paths:
      - .github/workflows/tf-test-yq-install.yml

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  check-yq:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    strategy:
      fail-fast: false
      matrix:
        app: [cdap]
        env: [mgmt]
    steps:
      - name: Install yq
        uses: cmsgov/cdap/actions/setup-yq@12577a9048a1bc13aae5e4e6d4b1224a91c279dc
      - name: Call yq
        run: |
          yq --version