name: tofu-fmt

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'terraform/**'

env:
  TENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: ./terraform

jobs:
  check:
    runs-on: codebuild-cdap-${{github.run_id}}-${{github.run_attempt}}
    steps:
      - uses: actions/checkout@0b65099ef9232cfa2dfd4eea89cf8b9fa6052013 # v5.0.0
      - uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159  # v3.9.2
      - uses: cmsgov/cdap/actions/setup-tenv@0b65099ef9232cfa2dfd4eea89cf8b9fa6052013
      - run: tofu fmt -check -diff -recursive .
